name: quiz_foot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  diacritic: ^0.1.3
  string_similarity: ^2.0.0
  collection: ^1.17.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 👇 Ajout pour générer les icônes
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/players.json
    - assets/images/ball.png
    - assets/images/logo.png
    - assets/images/logo_app.png
    - assets/images/correct.jpg
    - assets/images/wrong.jpg
    - assets/logos/competitions/
    - assets/logos/pays/
    - assets/logos/Champions League/
    - assets/logos/Austria - Bundesliga/
    - assets/logos/Belgium - Jupiler Pro League/
    - assets/logos/Bulgaria - efbet Liga/
    - assets/logos/Croatia - SuperSport HNL/
    - assets/logos/Czech Republic - Chance Liga/
    - assets/logos/Denmark - Superliga/
    - assets/logos/England - Premier League/
    - assets/logos/France - Ligue 1/
    - assets/logos/Germany - Bundesliga/
    - assets/logos/Greece - Super League 1/
    - assets/logos/Italy - Serie A/
    - assets/logos/Netherlands - Eredivisie/
    - assets/logos/Norway - Eliteserien/
    - assets/logos/Poland - PKO BP Ekstraklasa/
    - assets/logos/Portugal - Liga Portugal/
    - assets/logos/Romania - SuperLiga/
    - assets/logos/Russia - Premier Liga/
    - assets/logos/Scotland - Scottish Premiership/
    - assets/logos/Serbia - Super liga Srbije/
    - assets/logos/Spain - La Liga/
    - assets/logos/Sweden - Allsvenskan/
    - assets/logos/Switzerland - Super League/
    - assets/logos/Türkiye - Süper Lig/
    - assets/logos/Ukraine - Premier Liga/
    - assets/images/shirt.png

  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700

# 👇 Config pour flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21
