name: quiz_foot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  diacritic: ^0.1.3
  string_similarity: ^2.0.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 👇 Ajout pour générer les icônes
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/players.json
    - assets/images/ball.png
    - assets/images/logo.png
    - assets/images/logo_app.png
    - assets/images/correct.jpg
    - assets/images/wrong.jpg
    - assets/logos/

  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700

# 👇 Config pour flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21
