// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3wFpLsReftNfQOi4d0LQ0gLAI2TAA8zQ',
    appId: '1:577482120939:android:b9c4b2b5a3dddc88a928ae',
    messagingSenderId: '577482120939',
    projectId: 'tempo-ab8cd',
    storageBucket: 'tempo-ab8cd.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTPYNtXTPNNI0GuOqtmjfFV6wO2GjJ8_I',
    appId: '1:577482120939:web:8d2347c8f78e7b28a928ae',
    messagingSenderId: '577482120939',
    projectId: 'tempo-ab8cd',
    authDomain: 'tempo-ab8cd.firebaseapp.com',
    storageBucket: 'tempo-ab8cd.firebasestorage.app',
    measurementId: 'G-GNT1XTWPV9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALNIBvzQKZhws1OO67QQLQP3YwYRmTeDk',
    appId: '1:577482120939:ios:e67b6a79f2b5013ea928ae',
    messagingSenderId: '577482120939',
    projectId: 'tempo-ab8cd',
    storageBucket: 'tempo-ab8cd.firebasestorage.app',
    iosBundleId: 'com.example.quizFoot',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALNIBvzQKZhws1OO67QQLQP3YwYRmTeDk',
    appId: '1:577482120939:ios:598df2c596288e79a928ae',
    messagingSenderId: '577482120939',
    projectId: 'tempo-ab8cd',
    storageBucket: 'tempo-ab8cd.firebasestorage.app',
    iosBundleId: 'com.tempofoot.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTPYNtXTPNNI0GuOqtmjfFV6wO2GjJ8_I',
    appId: '1:577482120939:web:62c8052469cdb126a928ae',
    messagingSenderId: '577482120939',
    projectId: 'tempo-ab8cd',
    authDomain: 'tempo-ab8cd.firebaseapp.com',
    storageBucket: 'tempo-ab8cd.firebasestorage.app',
    measurementId: 'G-2NW6XNQE45',
  );

}